project:
  type: book
  output-dir: docs

execute:
  echo: true
  warning: false
  include: true

book:
  title: "Data Analysis using R"
  subtitle: "including what they forgot to teach you about computers"
  author: "Emma Rand"
  date: "March 2023"
  site-url: "https://3mmarand.github.io/combio/"
  chapters:
    - index.qmd
    - intro.qmd
    - file_systems.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

