project:
  type: book
  output-dir: docs

execute:
  echo: true
  warning: false
  include: true
  freeze: auto

# If you really need a site-url (for RSS, sitemap, etc), move it here:
website:
  site-url: https://3mmarand.github.io/comp4biosci/

book:
  title: "Computational Analysis for Bioscientists"
  subtitle: "Data Analysis in R and what they forgot to teach you about computers!"
  author: "Emma Rand"
  date: last-modified
  date-format: D MMMM, YYYY
  search: true

  page-footer:
    left: |
      Rand, E. (2025). Computational Analysis for Bioscientists  
      (Version 0.2) https://3mmarand.github.io/comp4biosci/

  repo-actions: [edit]  
  repo-url: https://github.com/3mmaRand/comp4biosci

  other-links:
    - text: "Report an issue"
      icon: bug
      # at render time, this expands to something like:
      # https://github.com/3mmaRand/comp4biosci/issues/new
      #   ?title=Intro%20to%20the%20Book
      #   &body=https://3mmarand.github.io/comp4biosci/intro.html
      href: |
        https://github.com/3mmaRand/comp4biosci/issues/new
        ?title={{< meta title >}}
        &body={{< meta book.site-url >}}{{< meta book.html.page-url-path >}}

  chapters:
    - index.qmd
    - intro.qmd
    
    - part: what-they-forgot.qmd
      chapters:
        - machine-and-os.qmd
        - file-systems.qmd
        - organising-work.qmd
    
    - part: getting-started-with-data.qmd
      chapters: 
        - ideas-about-data.qmd
        - about-R-and-RStudio.qmd
        - first-steps-rstudio.qmd
        - workflow-rstudio.qmd
        - import-to-report.qmd
        - recording-data.qmd
    
    - part: statistical-analysis-1.qmd
      chapters: 
        - logic-hyopthesis-testing.qmd
        - confidence-intervals.qmd
        - what-statistical-model.qmd
        - single-linear-regression.qmd
        - two-sample-tests.qmd
        - one-way-anova-and-kw.qmd
        - two-way-anova.qmd
        - association.qmd
        - goodness-of-fit.qmd      
    
    - part: working-with-gel-data.qmd
      chapters:
        - PCR-product-verification.qmd
        - molecular-weight-from-western-blot.qmd
   
    - part: in-development.qmd
      chapters:
        - 26C-food-fuel-prac2.qmd
    


    - summary.qmd
    - keyboard-shortcuts-tips.qmd
    - references.qmd

bibliography:
  - references.bib
  - references-libs.bib

format:
  html:

    theme:
      light: [cosmo, style.scss]
      dark:  [solar, style.scss]
    link-external-newwindow: true
    code-link: true
    mainfont: Atkinson Hyperlegible
    monofont: Source Code Pro
    lightbox:
      match: auto
      loop: false
