project:
  type: book
  output-dir: docs

execute:
  echo: true
  warning: false
  include: true
  freeze: auto
  

book:
  title: "Computational Analysis for Bioscientists"
  subtitle: "Data Analysis in R and what they forgot to teach you about computers!"
  author: "Emma Rand"
  date: last-modified
  date-format: D MMMM, YYYY
  search: true
  page-footer:
    left: |
      Rand, E. (2023). Computational Analysis for Bioscientists
      (Version 0.1) <https://3mmarand.github.io/comp4biosci/>
    
    # right:
    #   - icon: twitter
    #     href: https://twitter.com/er_13
    #     aria-label: Twitter
    #   - icon: github
    #     href: https://github.com/3mmaRand/comp4biosci
    #     aria-label: comp4biosci GitHub
    # 
  repo-actions: [edit, issue]
  repo-url: https://github.com/3mmaRand/comp4biosci
  site-url: https://3mmarand.github.io/comp4biosci/
  
  chapters:
    - index.qmd
    - intro.qmd
    
    - part: what_they_forgot.qmd
      chapters:
        - machine_and_os.qmd
        - file_systems.qmd
        - organising_work.qmd
    
    - part: getting_started_with_data.qmd
      chapters: 
        - ideas_about_data.qmd
        - first_steps_rstudio.qmd
        - workflow_rstudio.qmd
        - import_to_report.qmd
    
    - part: statistical_analysis_1.qmd
      chapters: 
        - logic_hyopthesis_testing.qmd
        - confidence_intervals.qmd
        - what_statistical_model.qmd
        - single_linear_regression.qmd
        - two_sample_tests.qmd
        - one_way_anova_and_kw.qmd
        - two_way_anova.qmd
        - association.qmd
        - goodness_of_fit.qmd      
    
    - part: working_with_gel_data.qmd
      chapters:
        - PCR_product_verification.qmd
        - molecular_weight_from_western_blot.qmd
   
    - part: in_development.qmd
      chapters:
        - 26C-food-fuel-prac2.qmd
    


    - summary.qmd
    - keyboard_shortcuts_tips.qmd
    - references.qmd

bibliography:
  - references.bib
  - references_libs.bib

format:
  html:
    link-external-newwindow: true
    code-link: true
    theme: 
      light: cosmo
      dark: solar

crossref:
  fig-title: '**Figure**'

metadata-files:
  - _downlit.yml

comments:
  hypothesis: true

editor: source

