project:
  type: book
  output-dir: docs

execute:
  echo: true
  warning: false
  include: true

book:
  title: "Computational Analysis for Bioscientists"
  subtitle: "Data Analysis in R and what they forgot to teach you about computers!"
  author: "Emma Rand"
  date: "March 2023"
  site-url: "https://3mmarand.github.io/combio/"
  chapters:
    - index.qmd
    - intro.qmd
    - part: what_they_forgot.qmd
      chapters: 
        - file_systems.qmd
    - part: getting_started_with_data.qmd
      chapters: 
        - ideas_about_data.qmd
        - first_steps_rstudio.qmd
        - working_with_data_rstudio.qmd
    - summary.qmd
    - keyboard-shortcuts-tips.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    code-link: true
    theme: 
      light: cosmo
      dark: solar
  pdf:
    documentclass: scrreprt

editor: visual

