# Getting started with data analysis in R {#sec-getting-started-with-data}

```{r}
#| results: "asis"
#| echo: false

source("_common.R")
status("polishing")
```

The first steps into analysing data with R. The first chapter in this
part covers important concepts about data: whether they are discrete and
continuous and how we summarise them using descriptive statistics. These
ideas are not specific to analysing data with R, they apply whatever
analysis tool you use. 

The second chapter introduces you to R and
RStudio for the first time. It explains what R, RStudio and R packages
are and where to find them. It then explores the layout and appearance.

In the third chapter you will start coding and lean the most common data
types and data structures used for data analysis. 

The fourth chapter describes some useful workflow patterns and tools for 
organising your work in RStudio. Using these will make learning R easier.

Finally, we will go through a complete workflow from importing data from a 
file to saving a figure for reporting.
