# In development

```{r}
#| results: "asis"
#| echo: false

source("_common.R")
status("drafting")
```

## 26C

### BIO1 Food and Fuel

游릴
*Pseudomonas putida* is a hydrocarbon-degrading bacterium which
can be used for cleaning up oil-contaminated soil. 

#### Prac 1 check the identity of Pseudomonas putida

-   Gram staining of your cultures
-   an oxidase test.
-   growth on a hydrocarbon substrate
-   PCR analysed by gel electrophoresis. The expected size of the 
    PCR product is 618 bp. The expectation is that you will
    see a band of this size for your Pseudomonas putida samples and 
    not for E. coli or the water control

#### Prac 2 Assay the number of bacteria with spot plates

游릴

Response: Number of bacteria
Two Explanatory: 
   soil: contaminated with hexadecane or not
   temperatuire: 4 degrees or 25 degrees



#### Prac 3 Design an experiment that uses methods from prac 2


### BIO2 Health and disease

#### Prac 1 
游릴
#### Prac 2 

#### Prac 3 


### BCH

#### Prac 1 

#### Prac 2 

#### Prac 3 


### BMS Anitbiotics and antimicrobial resistance

#### Prac 1 

#### Prac 2 

#### Prac 3 


## 66I

### Biomedical sciences

flow cytometry to assess the effect of LPS and E. coli on TNFalpha production in macrophages

游릴 SDS-PAGE and western blot to assess TNFalpha production in the whole cell population across the media, LPS, and E. coli stimulated macrophage samples.

assess size of the protein band in comparison to TNFalpha, and the strength of the protein signal in each sample


### Biotechnology


### Cell biology


### Molecular systema


### Gene expression and biochemical interactions
