# Machines and operating systems

```{r}
#| results: "asis"
#| echo: false

source("_common.R")
status("polishing")
```



## Computer or tablet?

Computers (laptop or desktop) and tablets can both be useful for doing a science degree but if you have to choose just one, I would recommend a computer. This is because

1.  Computers typically offer more processing power, storage capacity, and flexibility for running complex software all of which are important in science.

2.  Scientific and academic software often cannot be installed on tablets - at least not easily.

3.  Your institution most likely has a networked computer system with computers that you use in taught workshop and which are available to you throughout your degree. Many people find it easier to use a similar computer at home so they can follow instructions from the workshop exactly to continue the work at home

4.  We often need to multitask and use several programs at once. The greater power and screen size of a computer usually makes this easier.

Tablets are more portable and have touch-screens and stylus support and this makes them easier to use for note taking in lectures and annotating documents. Some laptops also have touch-screens but they can be expensive. Overtime computers will adopt more of the advantages of tablets and tablets will adopt more of the advantages of computers.

## What is an operating system?

Every computer or mobile device has an operating system (OS) which controls how all the other software on a computer interacts with the computer hardware. You may already have a preference for a particular OS. They start the computer up, manage the memory and all the processes, and control all the devices connected to the computer. As a consequence, all the other software on a computer has to be able to work with the operating system installed.

Most people do not install the operating system but buy their machine with it pre-installed.

## Types of operating system

### Microsoft Windows and Apple macOS

Windows and Mac are the two most widely used OS on personal computers. Apple Mac computers use only Apple macOS but Windows OS are used by many machine manufacturers. Both OS are proprietor meaning that they are designed and sold by the companies and are not meant to be altered by users. It also means the other applications they make are designed to work best with their OS.

You might already have had - or seen - a Mac versus Windows debate but in reality it is down to preference for most users. If you already have experience with one, you will probably prefer to keep using it but if you are buying for the first time, I recommend using the same as your institution uses. This makes it more likely that instructions for taught material will just work on your machine and more likely that people around you will be able to help.

One of the differences uses most notice between Windows and Mac machine is the keyboard keys names. Table @tbl-key-board gives some of the most notable.

| Windows | Mac     |
|---------|---------|
| Enter   | Return  |
| Control | Command |
| Alt     | Option  |


: Keyboard equivalents for Windows and Mac {#tbl-key-board}

When using RStudio, the section on [Keyboard Shortcuts and tips](keyboard_shortcuts_tips.qmd) will help.


### Linux 

Linux is a family of open source OS. Open source means that anyone can modify and share the software.

(TODO - expand)
