# Agarose gels for PCR product verfication

```{r}
#| results: "asis"
#| echo: false

source("_common.R")
status("drafting")
```

## 

## Do probiotic capsules contain *Lactobacillus acidophilus*?

*Lactobacillus acidophilus* probiotic capsules are widely available in
supermarkets and health food shops as health-promoting supplements. To
verify the identity of the bacteria within these capsules, primers
specific to *Lactobacillus acidophilus* were designed and used in a PCR
reaction. Three cell extracts were prepared from three bacterial
colonies: two isolated from probiotic capsules, and one from *E. coli*,
which was included as a negative control as it is not expected to be
amplified by the primers. Four PCR reaction tubes were prepared, one for
each cell extract and a forth as a no-template negative control. These
were loaded on to an electrophoresis gel along with a 100 base pair DNA
marker ladder

![Primers specific to *Lactobacillus acidophilus* were designed and and
used in a PCR reaction to confirm the identity of the bacteria isolated
from probiotic capsules. *E.coli* was used as a negative control. The
lanes from left to right are: 100 bp ladder, *Lacidophilus* colony 1,
*Lacidophilus* colony 2, *E.coli* colony, no template
control.](data-images/lactobacillus-gel-dna.png){width="400"}

## Is this bioremediation product *Pseudomonas putida*?

blah blah

![Primers specific to *Pseudomonas putida* were designed and and used in
a PCR reaction to confirm the identity of the bacteria isolated from a
bioremediation product. *E.coli* was used as a negative control. The
lanes from left to right are: 100 bp ladder, *Pseudomonas putida* colony
1, *Pseudomonas putida* colony 2, *E.coli* colony, no template
control.](data-images/pseudomonas-gel-dna.png){width="400"}
