# What is a statistical model

```{r}
#| results: "asis"
#| echo: false

source("_common.R")
status("drafting")
```

## 



- fit a relationship, examine how well the data fit


- measures of fit RSS, var explained by model vs variance left over


- test model parameters against zero

- general linear model the basis on many statistical tests

residuals
The assumptions of the general linear model are that the residuals are normally distributed and have homogeneity of variance. A residual is the difference between the predicted and observed value

in regression the predicted value is the value on the line. When you
have a theoretical explanatory variable, the predicted value is the
group mean. these are equivalent. the mean of one group is the
intercept; the mean of the other group is the slope

asumptions


regression, two sample, three sample


### Reporting

When reporting the results of statistical tests we need to make sure we tell the reader everything they need to know and give the evidence it to support it. What they need to know is given in statements describing what difference or effect is significant and the evidence is from the test statistic and *p*-value from the test. You can think the statistical test values as being the evidence for the statements in your results sections, just as citations are the evidence for the statements in your introduction.  

In reporting the result of a test we give:

1.  the significance of effect

2.  the direction of effect

3.  the magnitude of effect

figures should demonstrate the statement. should show the data and the
model


Supports your claim: 
-   how the data (all if possible) 
–   show the ‘model’ (the predicted values i.e., means and error bars) 
–   Say what kind of error bars/measures of dispersion
–   Full but concise figure legends
-   Figure legend https://blog.bioturing.com/2018/05/10/how-to-craft-a-figure-legend-for-scientific-papers/
-   refer to figure in text


