# What they forgot to teach you about computers

```{r}
#| results: "asis"
#| echo: false

source("_common.R")
status("polishing")
```

## Why "What they forgot"?

Most students grew up with the presence of digital technology and are
thought to be comfortable with, and fluent in, technology. But for many,
this fluency is with using tablets and smart phones and these are
different to computers. Several studies have shown that the increased
reliance on of tablets and smartphones makes people highly proficient at
online communication but hampers the development of other computing
skills [@drossel2017;
@australiancurriculumassessmentandreportingNationalAssessmentProgram2014].

This chapter tries to teach the computer skills that you might have
missed if you have used mainly the mobile devices. I focus on the
knowledge gaps that often appear when people are learning computational
data analysis. Primarily these are to do with finding and organising
their files and folders in the file systems.

If you often use a computer for tasks like organising files and writing
documents and spreadsheets much of this chapter might be familiar.
However, if you have mainly used your mobile phone and tablets to access
the internet then reading all of it will be helpful. The first chapter
briefly explains why a computer rather than a tablet is most useful for
a science degree and what an operating system is. The second chapter
some essential concept for scientific computers: file system
organisation, file types, working directories and paths. Most people
joining a bioscience degree programme are not familiar with the concept
of working directories but will find learning data analysis much easier
once they pick up this knowledge.
