on:
  push:
    branches: main

name: Render and Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - name: Install additional libraries on Linux
        if: runner.os == 'Linux'
        run: | 
          sudo apt-get update -y && sudo apt-get install -y libcurl4-openssl-dev
          sudo apt-get install -y libharfbuzz-dev 
          sudo apt-get install -y libfribidi-dev
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To install LaTeX to build PDF book 
          tinytex: true 
          # uncomment below and fill to pin a version
          # version: SPECIFIC-QUARTO-VERSION-HERE
      
      - uses: r-lib/actions/setup-renv@v2

      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          # The branch the action should deploy to.
          target: gh-pages
          # The folder the action should deploy. Adapt if you changed in Quarto config
          to: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions


     
 